### ISSUE TITLE
Total Pop Under 5 doesn't change post 2015

### ISSUE THREAD

**Issue by mattzook** [rgdonohue/who-hepB-dashboard#52]
Same issue as Infant Mortality.

stays with variable: U52015
should switch to variable: U52020

**Comment by rgdonohue** [comment]
@mattzook I'm confused by this one. The pattern for all the earlier years is that selecting a year displays the data from the earlier 5 or 10 year. So selecting 1996 uses the 1995 number, 2006 uses the 2005 number, but 2016 uses 2020?

**Comment by mattzook** [comment]
It looks like the function I am expecting now. For example

Year 2007 selected: Births & InfMort is 2005-2010)
Year 2010 selected: Births & InfMort is 2005-2010)
Year 2011 selected: Births & InfMort is 2010-2015)
Year 2015 selected: Births & InfMort is 2010-2015)
Year 2016 (and higher selected: Births & InfMort is 2015-2020)

**Comment by rgdonohue** [comment]
Okay, cool. I thought the issue was with the year listed in the parentheses after "Total Population under 5". Closing for now.
