### ISSUE TITLE
Tab 2 - Prevalence Graph - Y axis scale shift when toggled between 2015 and 2019 estimates

### ISSUE THREAD

**Issue by mattzook** [rgdonohue/who-hepB-dashboard#59]
We should have a standard y-axis scale to be able to compare.

**Comment by rgdonohue** [comment]
Okay, this one's gunna be a little tricky ... need to figure out which is higher (2015 vs 2019) for each chart for each country ... and use that.

**Comment by rgdonohue** [comment]
What a pain in the ass lol.
